"""Build land.js: which points of an even dot grid on the globe fall on land.

The globe is drawn from COUNT points spread evenly over a sphere (a Fibonacci
lattice). This script marks each point as land or sea and packs the answers
into a base64 bit string, so the page carries its own map and loads nothing.

Source: Natural Earth land, 1:50m (public domain), via the world-atlas package:
  curl -o land-50m.json https://cdn.jsdelivr.net/npm/world-atlas@2/land-50m.json
  python3 tools/make-land.py land-50m.json > land.js
"""

import base64
import json
import math
import sys

COUNT = 10000
W, H = 2880, 1440  # equirectangular raster, 8 cells per degree


def decode_arcs(topology):
    scale = topology["transform"]["scale"]
    shift = topology["transform"]["translate"]
    arcs = []
    for arc in topology["arcs"]:
        x = y = 0
        points = []
        for dx, dy in arc:
            x += dx
            y += dy
            points.append((x * scale[0] + shift[0], y * scale[1] + shift[1]))
        arcs.append(points)
    return arcs


def ring_points(ring, arcs):
    points = []
    for index in ring:
        arc = arcs[index] if index >= 0 else arcs[~index][::-1]
        points.extend(arc if not points else arc[1:])
    return points


def rasterize(rings):
    """Even-odd scanline fill of every ring into a W x H grid of booleans."""
    grid = [bytearray(W) for _ in range(H)]
    edges = []
    for ring in rings:
        for (x1, y1), (x2, y2) in zip(ring, ring[1:] + ring[:1]):
            edges.append((x1, y1, x2, y2))
    for row in range(H):
        lat = 90 - (row + 0.5) * 180 / H
        crossings = []
        for x1, y1, x2, y2 in edges:
            if (y1 > lat) != (y2 > lat):
                crossings.append(x1 + (lat - y1) * (x2 - x1) / (y2 - y1))
        crossings.sort()
        for start, end in zip(crossings[0::2], crossings[1::2]):
            c0 = max(0, int((start + 180) * W / 360 + 0.5))
            c1 = min(W, int((end + 180) * W / 360 + 0.5))
            grid[row][c0:c1] = b"\x01" * max(0, c1 - c0)
    return grid


def main(path):
    topology = json.load(open(path))
    arcs = decode_arcs(topology)
    rings = []
    for geometry in topology["objects"]["land"]["geometries"]:
        polygons = geometry["arcs"] if geometry["type"] == "MultiPolygon" else [geometry["arcs"]]
        for polygon in polygons:
            for ring in polygon:
                rings.append(ring_points(ring, arcs))
    grid = rasterize(rings)

    golden = math.pi * (3 - math.sqrt(5))
    bits = bytearray((COUNT + 7) // 8)
    land = 0
    for i in range(COUNT):
        lat = math.degrees(math.asin(1 - 2 * (i + 0.5) / COUNT))
        lon = math.degrees((i * golden) % (2 * math.pi)) - 180
        row = min(H - 1, int((90 - lat) * H / 180))
        col = min(W - 1, int((lon + 180) * W / 360))
        if grid[row][col]:
            bits[i >> 3] |= 1 << (i & 7)
            land += 1

    print("// Generated by tools/make-land.py from Natural Earth (public domain).")
    print(f"// {land} of {COUNT} lattice points are land.")
    print(f'window.LAND = {{ count: {COUNT}, bits: "{base64.b64encode(bits).decode()}" }};')


if __name__ == "__main__":
    main(sys.argv[1])
